

info:
  app:
    name: com.findout.slurper.api.russianconnection

spring:
  profiles.active: local
  rabbitmq:
      addresses: localhost
      port: 5672

logging:
  level:
    com.findout.softwarefactory.russianconnection: DEBUG

management:
  endpoint:
    web:
#      base-path: /
      exposure:
          include: health,info,env,metrics

server:
  port: 7878
  servlet:
    context-path: /api/

  bigpipe:
    url: http://localhost:7979

---

spring:
  profiles: localdocker

  rabbitmq:
    addresses: rabbitmq
    port: 5672

server:
  bigpipe:
    url: http://slurper-bigpipe:7979
